using System.Drawing;
using System.Windows.Forms;

namespace MAform {
    partial class MalwActivator {
        private System.ComponentModel.IContainer components;
        protected override void Dispose(bool disposing) {
            if (disposing && (components != null)) components.Dispose();
            base.Dispose(disposing);
        }
        private void InitializeComponent() {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MalwActivator));
            Tabs = new TabControl { Dock = DockStyle.Fill, Location = new Point(0, 0), Name = "Tabs", SelectedIndex = 0, Size = new Size(627, 234), SizeMode = TabSizeMode.FillToRight, TabIndex = 0 };
            ActivationTab = new TabPage { Location = new Point(4, 24), Name = "ActivationTab", Padding = new Padding(3), Size = new Size(619, 206), TabIndex = 0, Text = "Активация", UseVisualStyleBackColor = true };
            DownloadsTab = new TabPage { Location = new Point(4, 24), Name = "DownloadsTab", Padding = new Padding(3), Size = new Size(619, 206), TabIndex = 4, Text = "Скачивание", UseVisualStyleBackColor = true };
            FunctionsTab = new TabPage { Location = new Point(4, 24), Name = "FunctionsTab", Size = new Size(619, 206), TabIndex = 2, Text = "Другие функции", UseVisualStyleBackColor = true };
            ProblemsTab = new TabPage { Location = new Point(4, 24), Name = "ProblemsTab", Padding = new Padding(3), Size = new Size(619, 206), TabIndex = 1, Text = "Решение проблем", UseVisualStyleBackColor = true };
            Info = new TabPage { Location = new Point(4, 24), Name = "Info", Size = new Size(619, 206), TabIndex = 3, Text = "Информация", UseVisualStyleBackColor = true };
            tooltip = new ToolTip(components) { AutoPopDelay = 5000, InitialDelay = 5, ReshowDelay = 100 };
            radioButton1 = new RadioButton { AutoSize = true, Checked = true, Location = new Point(6, 6), Name = "radioButton1", Size = new Size(143, 19), TabIndex = 1, TabStop = true, Text = "Windows 10/11 (HWID)", UseVisualStyleBackColor = true };
            radioButton2 = new RadioButton { AutoSize = true, Location = new Point(6, 31), Name = "radioButton2", Size = new Size(130, 19), TabIndex = 2, Text = "Windows 8.1/8 KMS", UseVisualStyleBackColor = true };
            radioButton4 = new RadioButton { AutoSize = true, Location = new Point(214, 31), Name = "radioButton4", Size = new Size(83, 19), TabIndex = 4, Text = "Office 2021", UseVisualStyleBackColor = true };
            radioButton5 = new RadioButton { AutoSize = true, Location = new Point(6, 56), Name = "radioButton5", Size = new Size(193, 19), TabIndex = 5, Text = "Windows Server 2022/2019/2016", UseVisualStyleBackColor = true };
            radioButton6 = new RadioButton { AutoSize = true, Location = new Point(214, 106), Name = "radioButton6", Size = new Size(83, 19), TabIndex = 6, Text = "Office 2013", UseVisualStyleBackColor = true };
            radioButton7 = new RadioButton { AutoSize = true, Location = new Point(373, 6), Name = "radioButton7", Size = new Size(201, 19), TabIndex = 8, Text = "MultiMC/PolyMC/Prism Launcher", UseVisualStyleBackColor = true };
            radioButton8 = new RadioButton { AutoSize = true, Location = new Point(373, 31), Name = "radioButton8", Size = new Size(81, 19), TabIndex = 9, Text = "TLauncher", UseVisualStyleBackColor = true };
            radioButton9 = new RadioButton { AutoSize = true, Location = new Point(373, 56), Name = "radioButton9", Size = new Size(109, 19), TabIndex = 10, Text = "Macro Recorder", UseVisualStyleBackColor = true };
            radioButton10 = new RadioButton { AutoSize = true, Location = new Point(373, 81), Name = "radioButton10", Size = new Size(88, 19), TabIndex = 11, Text = "MobaXterm", UseVisualStyleBackColor = true };
            radioButton11 = new RadioButton { AutoSize = true, Location = new Point(373, 106), Name = "radioButton11", Size = new Size(64, 19), TabIndex = 12, Text = "Charles", UseVisualStyleBackColor = true };
            radioButton12 = new RadioButton { AutoSize = true, Location = new Point(373, 131), Name = "radioButton12", Size = new Size(244, 19), TabIndex = 13, Text = "Visual Studio 2022 Professional/Enterprise", UseVisualStyleBackColor = true };
            Activate = new Button { Location = new Point(515, 169), Name = "Activate", Size = new Size(96, 23), TabIndex = 14, Text = "Активировать!", UseVisualStyleBackColor = true };
            radioButton3 = new RadioButton { AutoSize = true, Location = new Point(214, 6), Name = "radioButton3", Size = new Size(79, 19), TabIndex = 15, Text = "Office 365", UseVisualStyleBackColor = true };
            radioButton13 = new RadioButton { AutoSize = true, Location = new Point(214, 81), Name = "radioButton13", Size = new Size(84, 19), TabIndex = 16, Text = "Office 2016", UseVisualStyleBackColor = true };
            radioButton14 = new RadioButton { AutoSize = true, Location = new Point(214, 56), Name = "radioButton14", Size = new Size(84, 19), TabIndex = 17, Text = "Office 2019", UseVisualStyleBackColor = true };
            DlWin10 = new Button { Location = new Point(8, 6), Name = "DlWin10", Size = new Size(83, 23), TabIndex = 0, Text = "Windows 10", UseVisualStyleBackColor = true };
            DlWin11 = new Button { Location = new Point(8, 64), Name = "DlWin11", Size = new Size(83, 23), TabIndex = 1, Text = "Windows 11", UseVisualStyleBackColor = true };
            DlWinLtsc = new Button { Location = new Point(8, 35), Name = "DlWinLtsc", Size = new Size(197, 23), TabIndex = 2, Text = "Win 10 LTSC 2021 (рекомендуется)", UseVisualStyleBackColor = true };
            Dl11Ltsc = new Button { Location = new Point(8, 93), Name = "Dl11Ltsc", Size = new Size(136, 23), TabIndex = 3, Text = "Windows 11 LTSC 2024", UseVisualStyleBackColor = true };
            Dl2022 = new Button { Location = new Point(215, 6), Name = "Dl2022", Size = new Size(136, 23), TabIndex = 4, Text = "Windows Server 2022", UseVisualStyleBackColor = true };
            button1 = new Button { Location = new Point(215, 35), Name = "button1", Size = new Size(136, 23), TabIndex = 5, Text = "Windows Server 2019", UseVisualStyleBackColor = true };
            button2 = new Button { Location = new Point(215, 64), Name = "button2", Size = new Size(136, 23), TabIndex = 6, Text = "Windows Server 2016", UseVisualStyleBackColor = true };
            button3 = new Button { Location = new Point(215, 93), Name = "button3", Size = new Size(136, 23), TabIndex = 7, Text = "Windows Server 2012", UseVisualStyleBackColor = true };
            button4 = new Button { Location = new Point(8, 122), Name = "button4", Size = new Size(83, 23), TabIndex = 8, Text = "Windows 8.1", UseVisualStyleBackColor = true };
            button5 = new Button { Location = new Point(437, 7), Name = "button5", Size = new Size(68, 23), TabIndex = 9, Text = "Online", UseVisualStyleBackColor = true };
            label2 = new Label { AutoSize = true, Location = new Point(362, 11), Name = "label2", Size = new Size(69, 15), TabIndex = 10, Text = "Office 2021:" };
            button6 = new Button { Location = new Point(522, 7), Name = "button6", Size = new Size(68, 23), TabIndex = 15, Text = "ISO", UseVisualStyleBackColor = true };
            label3 = new Label { AutoSize = true, Location = new Point(362, 39), Name = "label3", Size = new Size(70, 15), TabIndex = 16, Text = "Office 2019:" };
            label4 = new Label { AutoSize = true, Location = new Point(362, 68), Name = "label4", Size = new Size(70, 15), TabIndex = 17, Text = "Office 2016:" };
            label5 = new Label { AutoSize = true, Location = new Point(361, 97), Name = "label5", Size = new Size(69, 15), TabIndex = 18, Text = "Office 2013:" };
            button7 = new Button { Location = new Point(437, 36), Name = "button7", Size = new Size(68, 23), TabIndex = 19, Text = "Online", UseVisualStyleBackColor = true };
            button8 = new Button { Location = new Point(437, 65), Name = "button8", Size = new Size(68, 23), TabIndex = 20, Text = "Online", UseVisualStyleBackColor = true };
            button9 = new Button { Location = new Point(437, 93), Name = "button9", Size = new Size(68, 23), TabIndex = 21, Text = "Online", UseVisualStyleBackColor = true };
            button10 = new Button { Location = new Point(522, 36), Name = "button10", Size = new Size(68, 23), TabIndex = 22, Text = "ISO", UseVisualStyleBackColor = true };
            button11 = new Button { Location = new Point(522, 64), Name = "button11", Size = new Size(68, 23), TabIndex = 23, Text = "ISO", UseVisualStyleBackColor = true };
            button12 = new Button { Location = new Point(522, 93), Name = "button12", Size = new Size(68, 23), TabIndex = 24, Text = "ISO", UseVisualStyleBackColor = true };
            button20 = new Button { Location = new Point(6, 6), Name = "button20", Size = new Size(251, 23), TabIndex = 0, Text = "Узнать пароли от сохранённых Wi-Fi сетей", UseVisualStyleBackColor = true };
            button21 = new Button { Location = new Point(8, 35), Name = "button21", Size = new Size(113, 23), TabIndex = 1, Text = "Установить winget", UseVisualStyleBackColor = true };
            button22 = new Button { Location = new Point(127, 35), Name = "button22", Size = new Size(160, 23), TabIndex = 2, Text = "Установить Microsoft Store", UseVisualStyleBackColor = true };
            button23 = new Button { Location = new Point(263, 6), Name = "button23", Size = new Size(274, 23), TabIndex = 3, Text = "Отображать расширения файлов в проводнике", UseVisualStyleBackColor = true };
            button24 = new Button { Location = new Point(8, 64), Name = "button24", Size = new Size(208, 23), TabIndex = 4, Text = "Резервное копирование драйверов", UseVisualStyleBackColor = true };
            button25 = new Button { Location = new Point(222, 64), Name = "button25", Size = new Size(165, 23), TabIndex = 5, Text = "Восстановление драйверов", UseVisualStyleBackColor = true };
            button26 = new Button { Location = new Point(8, 93), Name = "button26", Size = new Size(208, 23), TabIndex = 6, Text = "Полностью удалить Microsoft Edge", UseVisualStyleBackColor = true };
            button27 = new Button { Location = new Point(222, 93), Name = "button27", Size = new Size(183, 23), TabIndex = 7, Text = "Удалить шпионские exe-файлы", UseVisualStyleBackColor = true };
            button13 = new Button { Location = new Point(48, 8), Name = "button13", Size = new Size(167, 23), TabIndex = 0, Text = "Очистить лицензии Office16", UseVisualStyleBackColor = true };
            button14 = new Button { Location = new Point(221, 8), Name = "button14", Size = new Size(176, 23), TabIndex = 1, Text = "Инструмент удаления Office", UseVisualStyleBackColor = true };
            button15 = new Button { Location = new Point(247, 71), Name = "button15", Size = new Size(260, 23), TabIndex = 2, Text = "Проверить системные файлы на целостность", UseVisualStyleBackColor = true };
            button16 = new Button { Location = new Point(48, 71), Name = "button16", Size = new Size(192, 23), TabIndex = 3, Text = "Сброс KMS-активации Windows", UseVisualStyleBackColor = true };
            button17 = new Button { Location = new Point(282, 136), Name = "button17", Size = new Size(175, 23), TabIndex = 4, Text = "Очистить кеш MalwActivator", UseVisualStyleBackColor = true };
            button18 = new Button { Location = new Point(403, 8), Name = "button18", Size = new Size(208, 43), TabIndex = 5, Text = "Обойти гео-ограничения на Online-установку Office", UseVisualStyleBackColor = true };
            pictureBox1 = new PictureBox { Image = (Image)resources.GetObject("pictureBox1.Image"), Location = new Point(8, 8), Name = "pictureBox1", Size = new Size(34, 39), TabIndex = 6, TabStop = false };
            pictureBox2 = new PictureBox { Image = (Image)resources.GetObject("pictureBox2.Image"), Location = new Point(8, 71), Name = "pictureBox2", Size = new Size(34, 39), TabIndex = 7, TabStop = false };
            button19 = new Button { Location = new Point(8, 165), Name = "button19", Size = new Size(154, 23), TabIndex = 8, Text = "У меня другая проблема!", UseVisualStyleBackColor = true };
            button28 = new Button { Location = new Point(8, 136), Name = "button28", Size = new Size(268, 23), TabIndex = 9, Text = "Исправить открытие ссылок Telegram Desktop", UseVisualStyleBackColor = true };
            button29 = new Button { Location = new Point(8, 23), Name = "button29", Size = new Size(109, 23), TabIndex = 0, Text = "Статья на Malw.ru", UseVisualStyleBackColor = true };
            label6 = new Label { AutoSize = true, Location = new Point(8, 5), Name = "label6", Size = new Size(102, 15), TabIndex = 1, Text = "MalwActivator 2.0" };
            button30 = new Button { Location = new Point(123, 23), Name = "button30", Size = new Size(109, 23), TabIndex = 2, Text = "Тема на Lolzteam", UseVisualStyleBackColor = true };
            button31 = new Button { Location = new Point(238, 23), Name = "button31", Size = new Size(56, 23), TabIndex = 3, Text = "GitHub", UseVisualStyleBackColor = true };
            label7 = new Label { AutoSize = true, Location = new Point(8, 91), Name = "label7", Size = new Size(86, 15), TabIndex = 4, Text = "Есть вопросы?" };
            button32 = new Button { Location = new Point(8, 109), Name = "button32", Size = new Size(124, 23), TabIndex = 5, Text = "Написать в Telegram", UseVisualStyleBackColor = true };
            button33 = new Button { Location = new Point(138, 109), Name = "button33", Size = new Size(156, 23), TabIndex = 6, Text = "Написать в теме Lolzteam", UseVisualStyleBackColor = true };
            button34 = new Button { Location = new Point(300, 109), Name = "button34", Size = new Size(156, 23), TabIndex = 7, Text = "Написать в Issues GitHub", UseVisualStyleBackColor = true };
            tooltip.SetToolTip(radioButton14, "Активация Office 2019 путём добавления файла sppc.dll\r\nАктивация сработает и для Office 365, 2016, 2021. Office потом автоматически конвертируется в 2019.\r\n");
            tooltip.SetToolTip(radioButton13, "Активация Office 2016 путём добавления файла sppc.dll\r\n2016 — уже давно устаревшая версия.\r\nАктивация сработает и для Office 365, 2019, 2021. Office потом автоматически конвертируется в 2016.\r\n");
            tooltip.SetToolTip(radioButton3, resources.GetString("radioButton3.ToolTip"));
            tooltip.SetToolTip(radioButton12, "Активировать Visual Studio 2022 Professional/Enterprise");
            tooltip.SetToolTip(radioButton11, "Получить ключ актиавции Charles 4.6.7");
            tooltip.SetToolTip(radioButton10, "Активировать MobaXterm последней версии. Если после активации MobaXterm перестал открываться, обновите его до последней версии на mobaxterm.mobatek.net");
            tooltip.SetToolTip(radioButton9, "Получить ключ актиавции Macro Recorder");
            tooltip.SetToolTip(radioButton8, "Отключить добавление рекламных серверов от TLauncher в раздел \"Сетевая игра\" в Minecraft");
            tooltip.SetToolTip(radioButton7, "Разрешить создание автономного аккаунта Minecraft в MultiMC, PolyMC или Prism Launcher без добавления аккаунта Microsoft");
            tooltip.SetToolTip(radioButton6, "Активация Office 2013 путём добавления файла sppc.dll");
            tooltip.SetToolTip(radioButton5, "Активация Windows Server 2022, Windows Server Standard, Windows Server Datacenter, 2019, 2016, 2012, 2012 R2, 1803, 1709");
            tooltip.SetToolTip(radioButton4, resources.GetString("radioButton4.ToolTip"));
            tooltip.SetToolTip(radioButton2, "Активация Windows 8 или Windows 8.1 через KMS");
            tooltip.SetToolTip(radioButton1, "Активация Windows 10 или 11 всех изданий (в том числе LTSC) по HWID");
            tooltip.SetToolTip(button12, resources.GetString("button12.ToolTip"));
            tooltip.SetToolTip(button11, resources.GetString("button11.ToolTip"));
            tooltip.SetToolTip(button10, resources.GetString("button10.ToolTip"));
            tooltip.SetToolTip(button9, resources.GetString("button9.ToolTip"));
            tooltip.SetToolTip(button8, resources.GetString("button8.ToolTip"));
            tooltip.SetToolTip(button7, resources.GetString("button7.ToolTip"));
            tooltip.SetToolTip(button6, resources.GetString("button6.ToolTip"));
            tooltip.SetToolTip(button5, resources.GetString("button5.ToolTip"));
            tooltip.SetToolTip(button4, "ISO образ Windows 8.1 с официального сайта Microsoft");
            tooltip.SetToolTip(button3, "ISO образ Windows Server 2012");
            tooltip.SetToolTip(button2, "ISO образ Windows Server 2016");
            tooltip.SetToolTip(button1, "ISO образ Windows Server 2019");
            tooltip.SetToolTip(Dl2022, "ISO образ Windows Server 2022");
            tooltip.SetToolTip(Dl11Ltsc, "ISO образ Windows 11 LTSC 2024. Английская версия! Русский язык можно будет поставить в Параметрах после установки.");
            tooltip.SetToolTip(DlWinLtsc, "ISO образ Windows 10 LTSC 2021");
            tooltip.SetToolTip(DlWin11, "ISO образ Windows 11 23H2 с официального сайта Microsoft\r\n");
            tooltip.SetToolTip(DlWin10, "ISO образ Windows 10 22H2 с официального сайта Microsoft");
            tooltip.SetToolTip(button27, "Удалить CompatTelRunner.exe и wsqmcons.exe");
            tooltip.SetToolTip(button25, "Перед переустановкой Windows лучше сделать резервную копию всех драйверов, чтобы потом не мучаться с ними после переустановки, а просто выбрать \"Восстановление\" здесь");
            tooltip.SetToolTip(button24, "Перед переустановкой Windows лучше сделать резервную копию всех драйверов, чтобы потом не мучаться с ними после переустановки, а просто выбрать \"Восстановление\" здесь");
            tooltip.SetToolTip(button22, "Только для LTSC-версий Windows без установленного Microsoft Store!");
            tooltip.SetToolTip(button20, "Перед запуском убедитесь, что Wi-Fi сейчас включен");
            tooltip.SetToolTip(button28, "Если у вас не открываются ссылки вида tg:// в Telegram Desktop, нажмите эту кнопку, затем выберите путь до Telegram.exe");
            tooltip.SetToolTip(button17, "Удалить папку %temp%\\MalwActivator");
            tooltip.SetToolTip(button15, "sfc /scannow и DISM /Online /Cleanup-Image /RestoreHealth");
            tooltip.SetToolTip(button14, "Скачать инструмент для полной очистки остаточных файлов Office");
            tooltip.SetToolTip(button13, "Очистит KMS-активацию Office 2021, 2019, 2016");
            Controls.Add(Tabs);
            Tabs.Controls.Add(ActivationTab);
            ActivationTab.Controls.Add(radioButton14);
            ActivationTab.Controls.Add(radioButton13);
            ActivationTab.Controls.Add(radioButton3);
            ActivationTab.Controls.Add(Activate);
            ActivationTab.Controls.Add(radioButton12);
            ActivationTab.Controls.Add(radioButton11);
            ActivationTab.Controls.Add(radioButton10);
            ActivationTab.Controls.Add(radioButton9);
            ActivationTab.Controls.Add(radioButton8);
            ActivationTab.Controls.Add(radioButton7);
            ActivationTab.Controls.Add(radioButton6);
            ActivationTab.Controls.Add(radioButton5);
            ActivationTab.Controls.Add(radioButton4);
            ActivationTab.Controls.Add(radioButton2);
            ActivationTab.Controls.Add(radioButton1);
            Tabs.Controls.Add(DownloadsTab);
            DownloadsTab.Controls.Add(button12);
            DownloadsTab.Controls.Add(button11);
            DownloadsTab.Controls.Add(button10);
            DownloadsTab.Controls.Add(button9);
            DownloadsTab.Controls.Add(button8);
            DownloadsTab.Controls.Add(button7);
            DownloadsTab.Controls.Add(label5);
            DownloadsTab.Controls.Add(label4);
            DownloadsTab.Controls.Add(label3);
            DownloadsTab.Controls.Add(button6);
            DownloadsTab.Controls.Add(label2);
            DownloadsTab.Controls.Add(button5);
            DownloadsTab.Controls.Add(button4);
            DownloadsTab.Controls.Add(button3);
            DownloadsTab.Controls.Add(button2);
            DownloadsTab.Controls.Add(button1);
            DownloadsTab.Controls.Add(Dl2022);
            DownloadsTab.Controls.Add(Dl11Ltsc);
            DownloadsTab.Controls.Add(DlWinLtsc);
            DownloadsTab.Controls.Add(DlWin11);
            DownloadsTab.Controls.Add(DlWin10);
            Tabs.Controls.Add(FunctionsTab);
            FunctionsTab.Controls.Add(button27);
            FunctionsTab.Controls.Add(button26);
            FunctionsTab.Controls.Add(button25);
            FunctionsTab.Controls.Add(button24);
            FunctionsTab.Controls.Add(button23);
            FunctionsTab.Controls.Add(button22);
            FunctionsTab.Controls.Add(button21);
            FunctionsTab.Controls.Add(button20);
            Tabs.Controls.Add(ProblemsTab);
            ProblemsTab.Controls.Add(button28);
            ProblemsTab.Controls.Add(button19);
            ProblemsTab.Controls.Add(pictureBox2);
            ProblemsTab.Controls.Add(pictureBox1);
            ProblemsTab.Controls.Add(button18);
            ProblemsTab.Controls.Add(button17);
            ProblemsTab.Controls.Add(button16);
            ProblemsTab.Controls.Add(button15);
            ProblemsTab.Controls.Add(button14);
            ProblemsTab.Controls.Add(button13);
            Tabs.Controls.Add(Info);
            Info.Controls.Add(button34);
            Info.Controls.Add(button33);
            Info.Controls.Add(button32);
            Info.Controls.Add(label7);
            Info.Controls.Add(button31);
            Info.Controls.Add(button30);
            Info.Controls.Add(label6);
            Info.Controls.Add(button29);
            AutoScaleDimensions = new SizeF(7F, 15F);
            AutoScaleMode = AutoScaleMode.Font;
            ClientSize = new Size(627, 234);
            FormBorderStyle = FormBorderStyle.FixedSingle;
            MaximizeBox = false;
            Name = "MalwActivator";
            Text = "MalwActivator";
            Tabs.ResumeLayout(false);
            ActivationTab.ResumeLayout(false);
            ActivationTab.PerformLayout();
            DownloadsTab.ResumeLayout(false);
            DownloadsTab.PerformLayout();
            FunctionsTab.ResumeLayout(false);
            ProblemsTab.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)pictureBox2).EndInit();
            ((System.ComponentModel.ISupportInitialize)pictureBox1).EndInit();
            Info.ResumeLayout(false);
            Info.PerformLayout();
            ResumeLayout(false);
            PerformLayout();
        }
        private TabControl Tabs;
        private TabPage ActivationTab;
        private TabPage ProblemsTab;
        private TabPage FunctionsTab;
        private TabPage Info;
        private RadioButton radioButton1;
        private ToolTip tooltip;
        private RadioButton radioButton4;
        private RadioButton radioButton2;
        private RadioButton radioButton6;
        private RadioButton radioButton5;
        private RadioButton radioButton7;
        private RadioButton radioButton12;
        private RadioButton radioButton11;
        private RadioButton radioButton10;
        private RadioButton radioButton9;
        private RadioButton radioButton8;
        private Button Activate;
        private TabPage DownloadsTab;
        private Button DlWinLtsc;
        private Button DlWin11;
        private Button DlWin10;
        private Button Dl2022;
        private Button Dl11Ltsc;
        private Label label2;
        private Button button5;
        private Button button4;
        private Button button3;
        private Button button2;
        private Button button1;
        private Button button7;
        private Label label5;
        private Label label4;
        private Label label3;
        private Button button6;
        private Button button12;
        private Button button11;
        private Button button10;
        private Button button9;
        private Button button8;
        private Button button16;
        private Button button15;
        private Button button14;
        private Button button13;
        private PictureBox pictureBox1;
        private Button button18;
        private Button button17;
        private PictureBox pictureBox2;
        private Button button19;
        private Button button21;
        private Button button20;
        private Button button25;
        private Button button24;
        private Button button23;
        private Button button22;
        private Button button27;
        private Button button26;
        private Button button28;
        private Label label7;
        private Button button31;
        private Button button30;
        private Label label6;
        private Button button29;
        private Button button33;
        private Button button32;
        private Button button34;
        private RadioButton radioButton3;
        private RadioButton radioButton14;
        private RadioButton radioButton13;
    }
}